# Generated by Django 5.0.4 on 2024-05-02 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoObras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnica', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('historia', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('tecnica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoobras')),
            ],
        ),
    ]
