# Generated by Django 4.0.4 on 2024-06-24 02:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ordenpago_detalleorden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='imagen'),
            preserve_default=False,
        ),
    ]
